### ISSUE TITLE
Fresh Install (docker) , Portals, Create - Error 

### ISSUE THREAD

**Issue by DALDEI** [axibase/atsd#530]
Install via docker
Sample portal work fine
Follow getting started guide
Portals -> Create 
Gets a blank page with error: 

This page isn’t working
idell unexpectedly closed the connection.
ERR_INCOMPLETE_CHUNKED_ENCODING

![image](https://user-images.githubusercontent.com/286113/38263525-533cc564-373e-11e8-9a90-b7ad212cb144.png)

Repeated via other methods such as Portal -> Configure -> Create, 
Same errors

Used different browsers and on Linux and Windows.

Debugger shows:
![image](https://user-images.githubusercontent.com/286113/38263618-870d3950-373e-11e8-82c5-c1f8d8d9bfe8.png)

**Comment by rodionos** [comment]
Hi David,

We were able to reproduce the problem. It's a defect in freemarker templates that was introduced in a recent release. ETA for the fix is tomorrow. I'll update this issue when the fix is available. 

Regards,

Sergei

**Comment by rodionos** [comment]
Hello David,

The problem with new portals is now fixed.

Follow these [steps](https://github.com/axibase/atsd/blob/master/administration/update.md#update-command-in-docker-container) to update your ATSD instance.

```
docker exec -it atsd /bin/bash
```

```
/opt/atsd/bin/update.sh
```

Thank you for raising the issue with us.

Best regards,

Sergei
