### ISSUE TITLE
UI configuration for non-root path on the server

### ISSUE THREAD

**Issue by cojack** [axibase/atsd#842]
Hi,
I encounter an additional problem with configuration for UI, I wish to have UI at some specific endpoint, like: `domain.com/path/where/ui/will/stay` but, the code is written to works only for `document-root` path like: `domain.com` so I finished at additional nxginx configuration for explicit replace some attributes like href, src, or even action for text/html and url for text/css it works, but it's ugly and it just work around. 
But maybe Im blind and miss some configuration part of UI how to switch that during installation?

My work around looks like this:

```nginx
    location ^~ /path/to/axibase/ {
        proxy_pass http://axibase:8088/;
        proxy_redirect default;
        proxy_set_header Accept-Encoding "";
        sub_filter_types text/xml text/css;
        sub_filter "<head>" "<head><base href=\"${scheme}://${host}/path/to/axibase/\" />";
        sub_filter "src='/" "src='";
        sub_filter "src=\"/" "src=\"";
        sub_filter "href=\"/" "href=\"";
        sub_filter "href='/" "href='";
        sub_filter "action='/" "action='";
        sub_filter "action=\"/" "action=\"";
        sub_filter "url(/web" "url(/path/to/axibase/web";
        sub_filter "url('/web" "url('/path/to/axibase/web";
        sub_filter "url(\"/web" "url(\"/path/to/axibase/web";
        sub_filter_once off;
    }
```
First two directives are for proxy connection to docker with proper handler for redirects and third one is to disable encoding for sub_filter directive.
Rest directives as sub_filter are for handle replace strings in content to proper way of working css/images/fonts and rest of assets.

So I have add a `<base />` to `<head>` to switch the `root` but all of the links was `absolute` because they start from `/` and this was pain in the ass, if you could replace it with `relative` one, it will be awesome, also add oportunity to specific a `<base />` in `<head>`, also path in css should be relative to content where they are served from.

Thanks in advance!

**Comment by rodionos** [comment]
@cojack 

We have reviewed the issue and it seems that it would require changing too much front-end code (adding base to pages) in ATSD. The change entails a lot of work without a clear benefit that would make ATSD UI better on its own merits. I'm inclined to keep things as they're.

**Comment by cojack** [comment]
@rodionos I understand that, so I will post my final solution for **nginx** `proxy_pass` with `sub_filter` for others, maybe they will be searching for similar issue.

```nginx
    location ^~ /path/to/axibase/ {
        proxy_pass http://axibase:8088/;
        proxy_redirect default;
        proxy_set_header Accept-Encoding "";
        sub_filter_types text/xml text/css;
        sub_filter "<head>" "<head><base href=\"${scheme}://${host}/path/to/axibase/\" />";
        sub_filter "src='/" "src='";
        sub_filter "src=\"/" "src=\"";
        sub_filter "href=\"/" "href=\"";
        sub_filter "href='/" "href='";
        sub_filter "action='/" "action='";
        sub_filter "action=\"/" "action=\"";
        sub_filter "url(/web" "url(/path/to/axibase/web";
        sub_filter "url('/web" "url('/path/to/axibase/web";
        sub_filter "url(\"/web" "url(\"/path/to/axibase/web";
        sub_filter_types text/javascript;
        sub_filter "/api/v1/" "/path/to/axibase/api/v1/";
        sub_filter_once off;
    }
```

Difference?

```nginx
        sub_filter_types text/javascript;
        sub_filter "/api/v1/" "/path/to/axibase/api/v1/";
```

Was missing for "Pages" view.

I didn't check widgets, so I guess I might missing few additional `sub_filters` but I will try to update this thread when I will catch something new.

Regards.

**Comment by rodionos** [comment]
Closing as this nice integration appears to be somewhat out of scope for core ATSD docs. Could be a great candidate for a reference article or a blog.
