### ISSUE TITLE
service script

### ISSUE THREAD

**Issue by jamesRUS52** [axibase/atsd#873]
Helo

Do you have init service script for axibase and axibase-collector on redhat 7/centos 7?

I can't find it in repository. It available only for tcollector e.g. here https://github.com/axibase/atsd/blob/master/integration/tcollector/README.md

**Comment by rodionos** [comment]
@jamesRUS52 - Sorry, we don't have a readily available service script for axibase-collector. ATSD, on the other hand, has service scripts which are installed as part of the RPM package installation.

**Comment by rodionos** [comment]
Closing - ATSD service is configured as part of deb/rpm package installation.
